### PR TITLE
Logging FAQ article searches.

### PR DESCRIPTION
**Pull request by frankmullenger**
FAQ searches are logged so that a record is kept of the search term used and the results pages and FAQ articles that were viewed as a result of the search. Includes functionality to rate and leave a comment about an FAQ article.

### CODE REVIEW

**Comment by d-rivera-c** [comment]
Hi @frankmullenger , thanks for the pull request :)

Since it's such a big feature, and it's a mix of feature and minor fixes, I think I'm going to cherry-pick+pull-request smaller groups of commits instead of merging the whole branch. Attribution will be maintain and I'll have a better overview of all the changes. 
I'll also be merging with develop instead of master.

Thanks so much for the contribution! I'll work on this for the next few days ;)

**Comment by camfindlay** [comment]
Anything I can do to help get these features into the upstream let me know :)

**Comment by camfindlay** [comment]
@frankmullenger yip good that you removed that dep, however does this now leave the form spammable? Perhaps it could take whatever the default spamprotection extension is installed?

**Comment by camfindlay** [comment]
Also think perhaps since this branch started from a known 1.0.0 version, it might be an easier approach to cherry pick changes since 1.0.0 on top of this branch - I've tried doing the other way locally (rebasing this on master) and it's a nightmare ;) Also tried splitting it up into separate feature... they are all interconnected so I think it just needs to be treated as a whole.

Could we tag the current master HEAD as a next 1.x, make a 1.0 branch for this and then bring together the search branch + changes since 1.0.0 as the new master and push up and tag as 2.0.0?

**Comment by frankmullenger** [comment]
@camfindlay: Yes you're quite right about the form being potentially spammable. However, I think spam protection is best left to developers to implement via the hook. Using UserForms as an example, forms are spammable out of the box, the SpamProtection module needs to be installed along with a protector module such as ReCaptcha or similar before an EditableSpamProtectorField is available to protect the forms. So we could take a similar approach here.

In terms of the branching, `develop` and `master` are at the same point now. We are trying a Gitflow approach, so this feature branch has been rebased on `develop` (I should've merged but never mind) and this pull request can be merged without conflicts into `develop`. The next steps would be merging into `master` and tagging a new release. This work is backwards compatible so it could potentially be a `1.2.0`.

We are thinking about the `2.0.0` version for changing FAQ objects to inherit from SiteTree so that they can more easily have versioning and workflow functionality added to them.

**Comment by camfindlay** [comment]
I'd support a 2.0.0 version using page types and lumberjack going forward.

**Comment by frankmullenger** [comment]
@camfindlay it's actually relatively seamless to move the FAQ model to inherit from Page instead based on my initial investigation so this may be followed up in the near future.

**Comment by camfindlay** [comment]
Great, some of the functionality (like the ratings) could be built as submodules too I think.

**Comment by frankmullenger** [comment]
Yeah I agree, we might pull the search tracking and ratings out to it's own module or at the least, implement some feature flags in the mean time.

**Pull request merged**
